# Generated by Django 5.1.6 on 2025-03-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_board_app', '0006_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
