# Generated by Django 5.1.6 on 2025-03-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_board_app', '0007_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('num_members', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Description',
                'verbose_name_plural': 'Descriptions',
            },
        ),
    ]
