# Generated by Django 5.1.6 on 2025-03-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_board_app', '0008_sitedescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitedescription',
            options={'verbose_name': 'Site Description', 'verbose_name_plural': 'Site Description'},
        ),
    ]
