# Generated by Django 5.1.6 on 2025-02-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarsettings',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='navbar/'),
        ),
    ]
