# Generated by Django 5.1.6 on 2025-02-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0003_alter_navbarsettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarsettings',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
