# Generated by Django 5.1.6 on 2025-02-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0005_alter_navbarsettings_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_one_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_two_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_one_link', models.CharField(blank=True, max_length=255, null=True)),
                ('button_two_link', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_image', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Hero Settings',
            },
        ),
    ]
