# Generated by Django 5.1.6 on 2025-02-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0006_herosettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosettings',
            name='bg_color',
            field=models.CharField(default='#111827', max_length=7),
        ),
    ]
