# Generated by Django 5.1.6 on 2025-02-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0008_herosettings_h1_text_herosettings_sub_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosettings',
            name='hero_active',
            field=models.BooleanField(default=False),
        ),
    ]
