# Generated by Django 5.1.6 on 2025-02-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0009_herosettings_hero_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosettings',
            name='featured_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='herosettings',
            name='featured_one_icon',
            field=models.FileField(blank=True, null=True, upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='herosettings',
            name='featured_one_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosettings',
            name='featured_three_icon',
            field=models.FileField(blank=True, null=True, upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='herosettings',
            name='featured_three_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosettings',
            name='featured_two_icon',
            field=models.FileField(blank=True, null=True, upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='herosettings',
            name='featured_two_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='navbarsettings',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='navbar_icon/'),
        ),
    ]
