# Generated by Django 5.1.6 on 2025-03-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0010_herosettings_featured_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#3498db', max_length=7)),
                ('secondary_color', models.CharField(default='#2c3e50', max_length=7)),
            ],
        ),
    ]
