# Generated by Django 5.1.6 on 2025-03-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0011_websitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitesettings',
            options={'verbose_name': 'Website Setting', 'verbose_name_plural': 'Website Settings'},
        ),
    ]
