# Generated by Django 5.1.6 on 2025-03-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosettings',
            name='text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
