# Generated by Django 5.1.6 on 2025-03-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0014_herosettings_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='button_color',
            field=models.CharField(default='#3498db', max_length=7),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='button_hover_color',
            field=models.CharField(default='#2980b9', max_length=7),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='button_hover_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='button_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
