# Generated by Django 5.1.6 on 2025-03-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0015_websitesettings_button_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
