# Generated by Django 5.1.6 on 2025-02-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_profile_email_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profection',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
