# Generated by Django 5.1.6 on 2025-02-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_profile_profection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profection',
            new_name='occupation',
        ),
    ]
